# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#fail_fast: True
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: check-docstring-first
          types: [python]
        - id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]
          types: [python]
        - id: check-executables-have-shebangs
        - id: check-case-conflict
          types: [python]
        - id: check-toml
        - id: check-yaml
          args: [ --allow-multiple-documents ]
    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
        - id: check-poetry
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
        - id: python-use-type-annotations
          types: [python]
        - id: python-no-log-warn
          types: [python]
    - repo: https://github.com/pycqa/isort
      rev: 5.11.5
      hooks:
        - id: isort
          name: isort
          args: ["--profile", "black"]
    - repo: https://github.com/python/black
      rev: 22.3.0
      hooks:
        - id: black
          args: [ --safe ]
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
        - id: flake8
          types: [python]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: check-ast
          types: [python]
