sennder:
  ba: carriers-and-drivers
  team: driver-app
  component: pizza-api-app
  project: pizza-api-app
  
staticEnvironment:
  - name: PORT
    value: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
livenessProbe:
  path: /api/health
readinessProbe:
  path: /api/health

