locals {
##############################################################
# Component Definition Structure
##############################################################

#   components_definitions = {
#     "${YOURCOMPONENTNAME}" = {
#       environment_variables = {} # Key/Value of your environment variables generated by terraform
#       secrets               = {} # Key Value for secrets converted as environment variable generated by terraform
#     }
#     "${YOURSECONDECOMPONENTNAME}" = {
#       environment_variables = {} # Key/Value of your environment variables generated by terraform
#       secrets               = {} # Key Value for secrets converted as environment variable generated by terraform
#     }
#   }

##############################################################

  components_definitions = {
    "pizza-api-app" = {

      environment_variables = merge(
        var.container_environment,
        {
          DB_HOST = module.rds.this_db_instance_address
          DB_PORT = module.rds.this_db_instance_port
          DB_NAME = module.rds.this_db_instance_name
        }
      )
      secrets = merge(
          var.container_secrets,
          {
            DB_USER     = module.rds.this_db_instance_username
            DB_PASSWORD = var.database_master_password
          }
        )

    }
  }
cluster_name = var.cluster_name_overwrite == "" ? "${var.env}-microservices-eks-cluster" : var.cluster_name_overwrite
}

module "senndernetes_config" {
  source  = "gitlab.com/sennder/terraform-module-eksconfig/platform"
  version = ">= 1, < 2"
  for_each = local.components_definitions

  cluster_name_overwrite = local.cluster_name

  kube_namespace = each.key
  component      = each.key

  env     = var.env
  team    = local.team
  ba      = local.ba
  project = local.project

  environment_variables = local.components_definitions[each.key].environment_variables
  secrets               = local.components_definitions[each.key].secrets
}
